-- Urban Threads Supabase schema
-- Run this in Supabase SQL Editor before enabling USE_SUPABASE=true

create table if not exists public.users (
  id bigserial primary key,
  first_name text not null default '',
  last_name text not null default '',
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users (email);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(10,2) not null check (price >= 0),
  original_price numeric(10,2),
  image text not null,
  images jsonb not null default '[]'::jsonb,
  description text not null default '',
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  rating numeric(3,2) not null default 0,
  reviews integer not null default 0,
  badge text,
  in_stock boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists video text;
alter table public.products add column if not exists videos jsonb not null default '[]'::jsonb;

create index if not exists idx_products_category on public.products (category);
create index if not exists idx_products_price on public.products (price);

-- Security hardening: lock down exposed tables
alter table public.users enable row level security;
alter table public.products enable row level security;

revoke all on table public.users from anon, authenticated;
revoke all on table public.products from anon, authenticated;

-- Additional relational state tables (catalog settings, cart, wishlist)
-- Run: backend/sql/supabase-relational-state.sql
